### ISSUE TITLE
bulk bibtex import

### ISSUE THREAD

**Issue by haluk** [lucastheis/django-publications#15]
Is there any way to import multiple entries rather than one by one as in `Import BibTex`?

**Comment by alvarouc** [comment]
Any update on this? I am getting the same error

**Comment by lucastheis** [comment]
The current development version shouldn't throw an error when it encounters characters like "{\u{g}}" (although it might still not interpret it 100% correctly). Can you tell me which version you are using and post the bibtex entry that's causing the problem?

**Comment by lucastheis** [comment]
Christian Glodt's fork uses the `bibtexparser` library instead of my bibtex parser. Maybe this works better for you:
      https://github.com/christianglodt/django-publications
Although it's planned, it will take me a while to completely replace the bibtex parser.
