### ISSUE TITLE
does not support django version 1.8

### ISSUE THREAD

**Issue by renpj** [lucastheis/django-publications#17]
I'm new in django. I have installed django-publications with django 1.8, didn't work. 
python manage.py runserver
gave the info:
/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)
WARNINGS:
publications.Publication.year: (fields.W122) 'max_length' is ignored when used with IntegerField
	HINT: Remove 'max_length' from field

Open it in browser, it returned blank page.

**Comment by lucastheis** [comment]
These errors are all just warning messages (mostly about things that will change with Django 1.9) and shouldn't prevent the app from working. Are you sure the app doesn't work? You might see a blank page only because there are no publications yet. Do you see the app when logging in to the admin area?

I made a few changes that should make the warning messages disappear (122230b).

**Comment by renpj** [comment]
Thanks, it works fine!
Maybe add some words or links in homepage, it helps people to work with this app, at least they can realize it has been successfully installed .
