### ISSUE TITLE
Pages field will only accept digits?

### ISSUE THREAD

**Issue by mick-t** [lucastheis/django-publications#18]
Hi,

I'm using django-publications and when I create a new publication using the admin I cannot create a publication with alphabetic or alphanumeric page numbers. See a screen shot [here](http://i.imgur.com/it9hPfW.png?1).

I'm looking at the code and it looks like it should support alphabetic and alphanumeric page numbers and I can create a Publication with alphanumeric page numbers:

```
In [39]: pub_2 = P.Publication.objects.get_or_create(type=t, title="bleb2", authors="bleb2", year="2004", pages="a")

In [40]: pub_2[0].first_page()
Out[40]: u'a'
```

I'm running Django 1.5.12, and it's django-publications from this commit

[git+https://github.com/lucastheis/django-publications.git@2972f80b51665343f90390b4826019238d682e1e](https://github.com/lucastheis/django-publications/commit/2972f80b51665343f90390b4826019238d682e1e)

We're running that version as  a junior developer decided to use it wasn't able to upgrade to a new version as there were no South migrations available. 

Let me know if you need any further debugging info!

Thanks
Mick

**Comment by mick-t** [comment]
I created a Publication object created using the Django Shell and assigned the page number 'a'. When I look at the in the Admin I see the pages as 'a' to 'a', clicking save shows an error messge. See this (screenshot)[http://imgur.com/8kRrdv5]

It may be a problem with the admin pages and not with the underlying model, or an issue with the PagesForm or the PagesWidget.

**Comment by mick-t** [comment]
See my pull request:

* https://github.com/lucastheis/django-publications/pull/19

**Comment by lucastheis** [comment]
Good point. I merged your pull request. Thanks!
