### ISSUE TITLE
Unescaping special characters in BibTex import

### ISSUE THREAD

**Issue by ewhitmire** [lucastheis/django-publications#20]
The bibtex import does not properly unescape percentage signs in a title.

For example, the following citation results in an extra slash in the title.
```
@inproceedings{kay2015good,
  title={How Good is 85\%? A Survey Tool to Connect Classifier Evaluation to Acceptability of Accuracy},
  author={Kay, Matthew and Patel, Shwetak N and Kientz, Julie A},
  booktitle={Proceedings of the 33rd Annual ACM Conference on Human Factors in Computing Systems},
  pages={347--356},
  year={2015},
  organization={ACM}
}
```

This results in the following formatted citation. Note the slash in the 85%.
>M. Kay, S. N. Patel, and J. A. Kientz 
How Good is 85\%? A Survey Tool to Connect Classifier Evaluation to Acceptability of Accuracy
Proceedings of the 33rd Annual ACM Conference on Human Factors in Computing Systems, 2015

**Comment by lucastheis** [comment]
Thanks ewhitmire, it's fixed in the development branch now (9d62ef79).
