### ISSUE TITLE
accept non-numerical characters in issue number field

### ISSUE THREAD

**Issue by mick-t** [lucastheis/django-publications#21]
The issue number of the Publication Model only accepts Integers. We often have Issue Numbers that are alphanumeric. i.e. issue a34.

I propose replacing the current IntegerField that's used with the PagesField (or a very similar custom Model) in the same or similar way that this pull request was implemented:
- https://github.com/lucastheis/django-publications/pull/19

I'll work on a version in my branch and will create a pull request within the next week.

Thanks
Mick

**Comment by mick-t** [comment]
I don't see any South migrations, how are you or would you prefer Model changes to be made? To try my propose change I'll need to change the number field in the Publication model from a IntergerField to a PagesField:

```number = models.IntegerField(blank=True, null=True, verbose_name='Issue number')```

to

```number = PagesField(blank=True, null=True, verbose_name='Issue number')```

**Comment by mick-t** [comment]
Hi, do you have any feedback on this? Thanks.

**Comment by mick-t** [comment]
While your thinking about this, I'll just use my own fork.

**Comment by mick-t** [comment]
Hello?

**Comment by lucastheis** [comment]
Sorry for not responding earlier, @mick-t. This seems like a rare problem and PagesField or CharField seem inappropriate for volume and issue number. At least I would like to keep the input fields in the form the same size to suggest that integers are expected, but unfortunately I currently don't have time to work on this.

**Comment by mick-t** [comment]
>At least I would like to keep the input fields in the form the same size to suggest that integers are expected, but unfortunately I currently don't have time to work on this.

I'm sorry, I'm not sure what you mean. Do you mean that you only expect integers for Issue Numbers? In our experience that's not the case and we just under 5,000 publications in our database.

**Comment by lucastheis** [comment]
I mean usually it will be an integer, and the interface looks cluttered if everything is just a CharField. Can you give some example publications?

**Comment by mick-t** [comment]
Here's a bunch:

https://www.ncbi.nlm.nih.gov/pubmed/?term=a13%5BIssue%5D
https://www.ncbi.nlm.nih.gov/pubmed/?term=d1%5BIssue%5D
