### ISSUE TITLE
unable to add a new document type

### ISSUE THREAD

**Issue by aubreymoore** [lucastheis/django-publications#27]
When I try to use the admin to add a new document type with the following:
type:  'Miscellaneous'
description: 'Miscellaneous'
bibtex_types: 'misc'

I get:
AttributeError at /admin/publications/type/add/
'Type' object has no attribute '_default_manager'

**Comment by lucastheis** [comment]
Do you know which version of django, django-publications and Python you are using?

**Comment by rschwiebert** [comment]
Python 3.6.2, Django 1.11, django-publications 0.6.2

`File "/env/lib/python3.6/site-packages/model_mommy/mommy.py", line 288, in instance
    instance.save(**_save_kwargs)
  File "/env/lib/python3.6/site-packages/publications/models/orderedmodel.py", line 66, in save
    c = self.get_ordering_queryset().aggregate(Max('order')).get('order__max')
  File "/env/lib/python3.6/site-packages/publications/models/orderedmodel.py", line 57, in get_ordering_queryset
    qs = qs or self._default_manager.all()
AttributeError: 'Type' object has no attribute '_default_manager'`

It looks like a similar problem to the one described above.
