### ISSUE TITLE
Add media delivery to installation documentation

### ISSUE THREAD

**Issue by AlexWillison** [lucastheis/django-publications#36]
It took a lot of searching to get the settings and urls correct to deliver PDFs and other media files.  Adding this info to the installation documentation would be helpful.  I posted what I had to do for Django 1.10 on StackOverflow [here](http://stackoverflow.com/questions/5517950/django-media-url-and-media-root/43546364#43546364).

**Comment by lucastheis** [comment]
This seems more like a question about Django then the django-publications app.

I agree it would be nice if there was an easier way to set up a website with django and django-publications properly installed and set up, but this seems beyond the scope of this app.
