### ISSUE TITLE
"Hidden" publications appearing in 'author', 'keyword', and 'list' views

### ISSUE THREAD

**Issue by AlexWillison** [lucastheis/django-publications#38]
While hidden publications do not appear in the 'year' view, they do appear in all other views.  This defeats the purpose of them being "hidden"

**Comment by lucastheis** [comment]
The hidden flag is meant to "hide publications from main view" and works as intended. You may not want certain types of publications like abstracts or patents in the main view, but still list them on an authors' page.

But I agree that adding an additional feature to temporarily hide certain publications from all views may be useful.
