### ISSUE TITLE
Using the Publication model

### ISSUE THREAD

**Issue by pjouzdani** [lucastheis/django-publications#39]
Hello I am new to Django and my question is likely silly. Also, I hope this is the right place to the question.

I installed this app, django-publications, and I am able to see it in the admin site. Now, I am trying to make a model, called Articles, and I would like to add a "citations" field to it. So, I was thinking to add a foreignkey to Publications model. However, I don't know how to this... 

models.ForeignKey(publications.models.Publication, on_delete=models.CASCADE)

does not work and gives error.

What is the right way to have a foreignKey to the Publications?

Thank you very much !

**Comment by rschwiebert** [comment]
@pjouzdani 
I want to do precisely the same thing. I didn't have any trouble with

`publication = models.ForeignKey('publications.Publication')
`
on my Citation model.  The makemigrations traceback was helpful: 

> ValueError: Invalid model reference 'publications.models.Publication'. String model references must be of the form 'app_label.ModelName'.

I didn't add the cascade, but I bet this should work for you...
