### ISSUE TITLE
Release the v0.7.0 branch

### ISSUE THREAD

**Issue by vdboor** [lucastheis/django-publications#40]
Hi @lucastheis, could you make a release of the v0.7.0 branch?

I've been using this code for some time now (on Django 1.11), and would like to replace the git-requirement with a PyPI installed package.

**Comment by lucastheis** [comment]
Unfortunately I currently don't have the resources to get v0.7.0 into a state where I would be happy to release it, sorry.

But you might find @mbourqui's fork useful:
https://github.com/mbourqui/django-publications-bootstrap

**Comment by vdboor** [comment]
Thanks for your update and honesty. I'll be checking this fork out.
