### ISSUE TITLE
How to add publications to a page

### ISSUE THREAD

**Issue by helvrud** [lucastheis/django-publications#45]
Hi would be great to add into documentation a few words about how to create page with list of publications.

**Comment by rschwiebert** [comment]
@helvrud Sounds like a basic Django question? Wouldn't you just put the publications in a list in the view context, then loop through them in the template to display?

**Comment by lucastheis** [comment]
The app by defaults creates a number of pages with lists of publications. If you follow the installation instructions, these should show up under '/publications'. For example, '/publications/year/2019' will list all publications for the year 2019.

The app also allows you to create custom lists of curated publications. These can be rendered with the provided template tags. In your django template, adding this should render the list:

```
{% load publication_extras %} 
{% get_publication_list <list_name> %}
```
